const quizData = [
  {
    question: 'Who was Juice WRLD?',
    a: 'Actor',
    b: 'Teacher',
    c: 'Rapper',
    d: 'Journalist',
    correct: 'c',
  },
  {
    question: 'Who is Mohamed Salah?',
    a: 'Actor',
    b: 'Football player',
    c: 'Singer',
    d: 'Tennis Player',
    correct: 'b',
  },
  {
    question: 'Who wrote the Song Lucid Dreams?',
    a: 'Lil Wayne',
    b: 'Eminem',
    c: '50 Cent',
    d: 'Juice WRLD',
    correct: 'd',
  },
  {
    question: 'Who wrote the Song In da Club?',
    a: '50 Cent',
    b: 'Wu-Tang',
    c: 'Redman',
    d: 'Eminem',
    correct: 'a',
  },
  {
    question: 'Who is Bruce Willis',
    a: 'Singer',
    b: 'Actor',
    c: 'Athlete',
    d: 'Thief',
    correct: 'b',
  },
  {
    question: 'Who is Denzel Washington?',
    a: 'Actor',
    b: 'Dancer',
    c: 'Athlete',
    d: 'Singer',
    correct: 'a',
  },
]
